src/core/AprOracle.sol
src/core/Factory.sol
src/core/Platform.sol
src/core/PriceReader.sol
src/core/StrategyLogic.sol
src/core/Swapper.sol
src/core/VaultManager.sol
src/interfaces/IAprOracle.sol
src/interfaces/IFactory.sol
src/interfaces/IPlatform.sol
src/interfaces/IPriceReader.sol
src/interfaces/IStrategyLogic.sol
src/interfaces/ISwapper.sol
src/interfaces/IVaultManager.sol
src/strategies/base/StrategyBase.sol
src/strategies/libs/StrategyLib.sol

Add Events

---

.github/workflows/semgrep.yml

* rules.solidity.performance.unnecessary-checked-arithmetic-in-loop

semgrep: setup rules

---

src/core/Factory.sol
src/core/Platform.sol
src/core/README.md
src/core/StrategyLogic.sol
src/core/VaultManager.sol
src/core/base/Controllable.sol
src/core/base/RVaultBase.sol
src/core/base/VaultBase.sol
src/interfaces/IFactory.sol
src/interfaces/IStrategy.sol
src/interfaces/IVault.sol
src/interfaces/IVaultManager.sol
src/strategies/GammaQuickSwapFarmStrategy.sol
src/strategies/QuickswapV3StaticFarmStrategy.sol
src/strategies/base/FarmingStrategyBase.sol
src/strategies/base/LPStrategyBase.sol
src/strategies/base/StrategyBase.sol
test/base/UniversalTest.sol
test/core/Factory.t.sol
test/core/Platform.Polygon.t.sol
test/core/Platform.t.sol
test/core/VaultManager.t.sol

ERC-165: Standard Interface Detection

---

src/core/HardWorker.sol
src/interfaces/IHardWorker.sol
test/core/Platform.Polygon.t.sol

https://eips.ethereum.org/EIPS/eip-7201

Namespaced storage: HardWorker

---

src/core/Platform.sol
src/core/VaultManager.sol
src/interfaces/IAmmAdapter.sol
src/interfaces/IPlatform.sol
src/interfaces/IVaultManager.sol
test/core/Platform.Polygon.t.sol
test/core/Platform.t.sol

The view functions needs to be implemented and refactored to effectively integrate with the frontend (stability-ui).
* `IPlatform.getData`
* On-chain UI vault list: `IVaultManager.vaults()`
* Vault info: implement `IVaultManager.vaultInfo(address vault)`

UI getters

---

script/libs/DeployLib.sol
script/libs/DeployStrategyLib.sol
src/core/AprOracle.sol
src/core/Factory.sol
src/core/Platform.sol
src/core/PriceReader.sol
src/core/StrategyLogic.sol
src/core/Swapper.sol
src/core/VaultManager.sol
src/core/libs/FactoryLib.sol
src/core/proxy/StrategyProxy.sol
src/core/vaults/CVault.sol
src/core/vaults/RMVault.sol
src/core/vaults/RVault.sol
src/interfaces/IFactory.sol
src/interfaces/IPlatform.sol
src/interfaces/ISwapper.sol
src/interfaces/IVault.sol
src/strategies/libs/StrategyLib.sol
src/test/MockVaultUpgrade.sol
test/base/UniversalTest.sol
test/core/Factory.t.sol
test/core/Platform.t.sol
test/core/Proxy.t.sol
test/core/Swapper.Polygon.t.sol
test/core/Vault.t.sol

2 namespaced storage

---

src/interfaces/IFarmingStrategy.sol
src/interfaces/ILPStrategy.sol
src/interfaces/IStrategy.sol
src/strategies/GammaQuickSwapFarmStrategy.sol
src/strategies/QuickswapV3StaticFarmStrategy.sol
src/strategies/base/FarmingStrategyBase.sol
src/strategies/base/LPStrategyBase.sol
src/strategies/base/StrategyBase.sol
src/strategies/libs/LPStrategyLib.sol
src/strategies/libs/StrategyLib.sol

* decrease code size
* refactor base strategy interfaces

Base strategies refactoring

---

src/core/base/RVaultBase.sol
src/core/base/VaultBase.sol
src/core/libs/RVaultLib.sol
src/interfaces/IRVault.sol
src/interfaces/IVault.sol

RVaultBase decrease size, refactoring

---

chains/PolygonLib.sol
script/DeployCF.Polygon.s.sol
script/libs/DeployStrategyLib.sol
src/integrations/compound/IComet.sol
src/integrations/compound/ICometRewards.sol
src/strategies/CompoundFarmStrategy.sol
src/strategies/libs/StrategyDeveloperLib.sol
src/strategies/libs/StrategyIdLib.sol
src/strategies/libs/StrategyLib.sol
test/base/UniversalTest.sol
test/strategies/CF.Polygon.t.sol

`0x1FeC24a11A34b2ff2113B75d38375475eF0D1562`

CompoundFarm

---

script/DeployUpdateStrategyGQMF.Polygon.sol
src/strategies/GammaQuickSwapMerklFarmStrategy.sol
test/base/UniversalTest.sol
test/strategies/GQMF.DebugDeposit.Polygon.sol

GQMF 1.0.1

---

chains/PolygonLib.sol
script/DeployStrategyCCF.Polygon.s.sol
script/DeployStrategyIRMF.Polygon.s.sol
script/libs/DeployStrategyLib.sol
src/integrations/convex/IBooster.sol
src/integrations/convex/IConvexRewardPool.sol
src/integrations/curve/IStableSwapNGPool.sol
src/strategies/CurveConvexFarmStrategy.sol
src/strategies/README.md
src/strategies/base/FarmingStrategyBase.sol
src/strategies/libs/StrategyDeveloperLib.sol
src/strategies/libs/StrategyIdLib.sol
src/strategies/libs/StrategyLib.sol
test/base/UniversalTest.sol
test/core/Platform.Polygon.t.sol
test/core/Vault.t.sol
test/strategies/CCF.Polygon.t.sol

Curve Convex Farm

---

src/interfaces/IFarmingStrategy.sol
src/strategies/CompoundFarmStrategy.sol
src/strategies/CurveConvexFarmStrategy.sol
src/strategies/DefiEdgeQuickSwapMerklFarmStrategy.sol
src/strategies/GammaQuickSwapMerklFarmStrategy.sol
src/strategies/GammaRetroMerklFarmStrategy.sol
src/strategies/IchiQuickSwapMerklFarmStrategy.sol
src/strategies/IchiRetroMerklFarmStrategy.sol
src/strategies/QuickSwapStaticMerklFarmStrategy.sol
src/strategies/base/FarmingStrategyBase.sol
test/base/UniversalTest.sol

* `stakingPool`
* FarmingStrategyBase 1.1.2
* CompoundFarmStrategy 1.1.1
* CurveConvexFarmStrategy 1.0.1
* DefiEdgeQuickSwapMerklFarmStrategy 1.1.1
* GammaQuickSwapMerklFarmStrategy 1.1.1
* GammaRetroMerklFarmStrategy 2.0.1
* IchiQuickSwapMerklFarmStrategy 1.1.1
* IchiRetroMerklFarmStrategy 2.0.1
* QuickSwapStaticMerklFarmStrategy 1.0.1

FarmingStrategyBase stakingPool

---

.github/workflows/test.yml
ADM.md
chains/BaseLib.sol
foundry.toml
src/core/README.md
src/interfaces/IFarmingStrategy.sol
src/strategies/CompoundFarmStrategy.sol
src/strategies/CurveConvexFarmStrategy.sol
src/strategies/DefiEdgeQuickSwapMerklFarmStrategy.sol
src/strategies/GammaQuickSwapMerklFarmStrategy.sol
src/strategies/GammaRetroMerklFarmStrategy.sol
src/strategies/GammaUniswapV3MerklFarmStrategy.sol
src/strategies/IchiQuickSwapMerklFarmStrategy.sol
src/strategies/IchiRetroMerklFarmStrategy.sol
src/strategies/QuickSwapStaticMerklFarmStrategy.sol
src/strategies/base/FarmingStrategyBase.sol
src/strategies/libs/StrategyLib.sol
test/strategies/IQMF.Upgrade.Polygon.t.sol

* IFarmingStrategy.refreshFarmingAssets, IFarmingStrategy.farmingAssets
* CF 1.1.1
* IQMF 1.3.0 [0x4fb0e05e44c7e28926090efd69b42207e148b4c1](https://polygonscan.com/address/0x4fb0e05e44c7e28926090efd69b42207e148b4c1)
* CCF 1.1.0
* DQMF 1.3.0
* GQMF 1.3.0
* GRMF 2.2.0
* GUMF 1.1.0
* IRMF 2.2.0
* QSMF 1.2.0

Farming upgrade, fmt setup, fix Base lib

---

src/strategies/TridentPearlFarmStrategy.sol
test/strategies/TPF.Upgrade.Real.t.sol

deployed at https://explorer.re.al/address/0x79ada896563c27a1333a30979f7b491aecc5934b

TPF 1.1.0: zero pool price bugfix

---

ADM.md
chains/SonicLib.sol
script/deploy-adapter/AlgebraV4.Sonic.s.sol
script/deploy-strategy/ISF.s.sol
script/libs/DeployAdapterLib.sol
src/adapters/AlgebraV4Adapter.sol
src/adapters/libs/AmmAdapterIdLib.sol
src/integrations/algebrav4/IAlgebraPool.sol
src/integrations/algebrav4/IVolatilityOracle.sol
src/integrations/algebrav4/pool/IAlgebraPoolActions.sol
src/integrations/algebrav4/pool/IAlgebraPoolErrors.sol
src/integrations/algebrav4/pool/IAlgebraPoolEvents.sol
src/integrations/algebrav4/pool/IAlgebraPoolImmutables.sol
src/integrations/algebrav4/pool/IAlgebraPoolPermissionedActions.sol
src/integrations/algebrav4/pool/IAlgebraPoolState.sol
src/integrations/ichi/IICHIVaultV4.sol
src/integrations/swapx/IGaugeV2_CL.sol
src/integrations/swapx/IVoterV3.sol
src/strategies/IchiSwapXFarmStrategy.sol
src/strategies/libs/ISFLib.sol
src/strategies/libs/StrategyDeveloperLib.sol
src/strategies/libs/StrategyIdLib.sol
test/adapters/AlgebraV4Adapter.Sonic.t.sol
test/base/UniversalTest.sol
test/base/chains/SonicSetup.sol
test/strategies/BSF.Sonic.t.sol
test/strategies/EF.Sonic.t.sol
test/strategies/ISF.Sonic.t.sol

ISF, AlgebraV4 adapter

---

script/upgrade-core/PrepareUpgrade.23.12.1-alpha.s.sol
script/upgrade-core/PrepareUpgrade.23.12.2-alpha.s.sol
script/upgrade-core/PrepareUpgrade.24.01.0-alpha.Polygon.s.sol
script/upgrade-core/PrepareUpgrade.24.05.0-alpha.s.sol
script/upgrade-core/PrepareUpgrade.24.06.1-alpha.s.sol
script/upgrade-core/PrepareUpgrade.25.01.1-alpha.s.sol
src/core/Zap.sol
test/core/Zap.Upgrade.Sonic.t.sol

0x068a5a4c82c80177cb7b4b6dc7e635cc27acd9b0

Zap 1.0.3: bugfix for Ichi deposit

---

src/interfaces/IStrategy.sol
src/strategies/BeetsStableFarm.sol
src/strategies/BeetsWeightedFarm.sol
src/strategies/CompoundFarmStrategy.sol
src/strategies/CurveConvexFarmStrategy.sol
src/strategies/DefiEdgeQuickSwapMerklFarmStrategy.sol
src/strategies/EqualizerFarmStrategy.sol
src/strategies/GammaQuickSwapMerklFarmStrategy.sol
src/strategies/GammaRetroMerklFarmStrategy.sol
src/strategies/GammaUniswapV3MerklFarmStrategy.sol
src/strategies/IchiQuickSwapMerklFarmStrategy.sol
src/strategies/IchiRetroMerklFarmStrategy.sol
src/strategies/IchiSwapXFarmStrategy.sol
src/strategies/QuickSwapStaticMerklFarmStrategy.sol
src/strategies/SteerQuickSwapMerklFarmStrategy.sol
src/strategies/SwapXFarmStrategy.sol
src/strategies/TridentPearlFarmStrategy.sol
src/strategies/YearnStrategy.sol
src/strategies/base/FarmingStrategyBase.sol
src/strategies/base/LPStrategyBase.sol
src/strategies/base/StrategyBase.sol
src/strategies/libs/DQMFLib.sol
src/strategies/libs/GRMFLib.sol
src/strategies/libs/LPStrategyLib.sol
src/strategies/libs/StrategyLib.sol
test/strategies/SF.Upgrade.Sonic.t.sol

SF 0x767950EdB5a31E4465E558Ed7f44E253f265A320

customPriceImpactTolerance

---

.github/workflows/slither.yml
chains/SonicLib.sol
src/strategies/ALMShadowFarmStrategy.sol
src/strategies/base/FarmingStrategyBase.sol
src/strategies/libs/StrategyLib.sol
test/strategies/ASF.Sonic.t.sol
test/strategies/ASF.Upgrade3.Sonic.t.sol
test/strategies/ISF.Sonic.t.sol
test/strategies/SiF.Sonic.sol

0xf4e2bedeBA5cE45071505175D4a5D19209d631A9

ALMShadowFarmStrategy 1.1.3; FarmingStrategyBase 1.3.2: refreshFarmingAssets bugfix

---

src/integrations/algebrav4/callback/IAlgebraFlashCallback.sol
src/interfaces/IControllable.sol
src/interfaces/ILeverageLendingStrategy.sol
src/strategies/SiloAdvancedLeverageStrategy.sol
src/strategies/base/LeverageLendingBase.sol
src/strategies/libs/SiloAdvancedLib.sol
test/strategies/SiAL.Sonic.sol
test/strategies/SiAL.Upgrade2.Sonic.t.sol

https://sonicscan.org/address/0x086a34b567e8b4247ac74ae41284a64dfab67e49

276 sial support swapx flashloan

---

src/interfaces/ILeverageLendingStrategy.sol
src/strategies/SiloAdvancedLeverageStrategy.sol
src/strategies/SiloLeverageStrategy.sol
src/strategies/base/LeverageLendingBase.sol
src/strategies/libs/LeverageLendingLib.sol
src/strategies/libs/SiloAdvancedLib.sol
src/strategies/libs/SiloLib.sol
test/strategies/SiAL.Sonic.sol
test/strategies/SiAL.Upgrade2.Sonic.t.sol
test/strategies/SiL.Sonic.sol
test/strategies/SiL.Upgrade2.Sonic.t.sol
test/strategies/libs/SiloAdvancedLib.t.sol
test/strategies/libs/SiloLib.t.sol

* SiL 2.0.0 https://sonicscan.org/address/0x2c4b9b522d3e9b4232ef469c332c4429c27a5368#code
* SiAL 2.2.0 https://sonicscan.org/address/0x7fbc84ca2783d2b70d648ef009d98be6b6410066#code

sil and sial fixes

---

README.md
guides/ADM.md
guides/AllDeployments.md
src/core/base/VaultBase.sol
src/core/vaults/CVault.sol
src/core/vaults/MetaVault.sol
src/interfaces/IMetaVault.sol
src/interfaces/IStabilityVault.sol
src/interfaces/IVault.sol
src/test/MockMetaVaultUpgrade.sol
src/test/MockVaultUpgrade.sol
test/core/CVault.Upgrade2.Sonic.t.sol
test/core/MetaVault.Upgrade.Sonic.t.sol
test/strategies/SiL.LeverageDebug.Sonic.t.sol

* CVault 1.7.0 https://sonicscan.org/address/0x836152c0b502f281390f96922361026ff04a24ff#code
* MetaVault 1.1.0 https://sonicscan.org/address/0xebd907742a9aa8f73bd24c3a2467b3f1af6407b6

lastBlockDefenseDisabled

---

chains/sonic/SonicConstantsLib.sol
guides/ADM.md
src/core/vaults/MetaVault.sol
src/core/vaults/WrappedMetaVault.sol
test/base/ERC4626Test.sol
test/core/MetaVault.Sonic.t.sol
test/core/MetaVault.Upgrade.Sonic.t.sol
test/core/MetaVault.Upgrade2.Sonic.t.sol
test/core/Wrapper.metaUSDC.ERC4626.Upgrade.Sonic.t.sol

* MetaVault 1.2.0 https://sonicscan.org/address/0x52a953d8c91b2d264d2ce3c0edf589e8d2eaedcc
* WrappedMetaVault 1.0.1 https://sonicscan.org/address/0xad122555e4c63f0e58a911fcfdce15433d038270#code

MetaVault 1.2.0, WrappedMetaVault 1.0.1

---

.gitignore
src/periphery/RebalanceHelper.sol
src/strategies/ALMShadowFarmStrategy.sol
src/strategies/libs/ALMLib.sol
src/strategies/libs/ALMRamsesV3Lib.sol
test/strategies/ASF.RebalanceTrigger.Sonic.t.sol
test/strategies/ASF.Upgrade4.Sonic.t.sol

* ASF 1.2.0 https://sonicscan.org/address/0xba7f6d9b214a22cdc40a3cd0e75cafff8294771b
* RebalanceHelper 1.1.0 https://sonicscan.org/address/0x659119200de09f266f3256a70986713ca1ee04d8#code

ASF 1.2.0: add limit rebalance trigger

---

src/adapters/BalancerComposableStableAdapter.sol
src/adapters/BalancerV3StableAdapter.sol
src/adapters/BalancerWeightedAdapter.sol
src/adapters/libs/balancer/FixedPoint.sol
src/adapters/libs/balancer/LegacyOZMath.sol
src/adapters/libs/balancer/LogExpMath.sol
src/adapters/libs/balancer/StableMath.sol
src/adapters/libs/balancer/WeightedMath.sol
src/adapters/libs/balancerv3/FixedPoint.sol
src/adapters/libs/balancerv3/LogExpMath.sol
src/adapters/libs/balancerv3/ScalingHelpers.sol
src/adapters/libs/balancerv3/StableMath.sol

Here we collect all the uncovered areas in the code base with a description of how to cover them.

Improve contracts coverage

---

src/core/base/VaultBase.sol
src/core/vaults/CVault.sol
src/core/vaults/MetaVault.sol
src/core/vaults/WrappedMetaVault.sol
src/strategies/SiloStrategy.sol
src/strategies/base/ERC4626StrategyBase.sol
src/strategies/libs/StrategyLib.sol
test/base/ERC4626Test.sol
test/core/Wrapper.metaUSDC.ERC4626.Upgrade.Sonic.t.sol
test/core/Wrapper.metascUSD.ERC4626.Upgrade.Sonic.t.sol

* MetaVault 1.2.1 https://sonicscan.org/address/0xe574aa020b313d813ebb3accbde6dd706dff6bd8#code
* WrappedMetaVault 1.0.2 https://sonicscan.org/address/0xd873360f00fb0fd23ef2819992faa4afeeea7573#code
* SiloStrategy 1.0.1 https://sonicscan.org/address/0x7a5ac22de8f3da3dabb7bcf14a23c4d3a17a8f51#code
* CVault 1.7.1 https://sonicscan.org/address/0xc24646f2b817e907397d05cff739794808e43753#code
* MetaVault 1.2.2 https://sonicscan.org/address/0x6f341c5F9AF9390A11C0bfcd49917640452757d0#code

WrappedMetaVault: metascUSD not pass ERC4626UniversalTest

---

src/core/base/VaultBase.sol
src/core/vaults/CVault.sol
src/interfaces/IStrategy.sol
src/strategies/ALMShadowFarmStrategy.sol
src/strategies/AaveStrategy.sol
src/strategies/BeetsStableFarm.sol
src/strategies/BeetsWeightedFarm.sol
src/strategies/EqualizerFarmStrategy.sol
src/strategies/EulerStrategy.sol
src/strategies/GammaUniswapV3MerklFarmStrategy.sol
src/strategies/IchiSwapXFarmStrategy.sol
src/strategies/SiloAdvancedLeverageStrategy.sol
src/strategies/SiloFarmStrategy.sol
src/strategies/SiloLeverageStrategy.sol
src/strategies/SiloManagedFarmStrategy.sol
src/strategies/SiloStrategy.sol
src/strategies/SwapXFarmStrategy.sol
src/strategies/base/StrategyBase.sol
src/test/MockStrategy.sol
test/core/CVault.Upgrade2.Sonic.t.sol
test/core/CVault.UpgradeAudit.Sonic.t.sol
test/core/MetaVault.Upgrade.Sonic.t.sol

- CVault 1.8.0: 0xba2AF2C17CADf0d5Cc904B0E8463775b3900c9aD
- ALMShadowFarmStrategy 1.3.0: 0x4dedeD159dD900Abf1889771Cf24496813cdD63D 
- AaveStrategy 1.1.0: 0x4ab51f16cd53eE07A90665d6612b5417668A1062
- BeetsStableFarm 1.2.0: 0x2d67dF704027bcc1A3cBa4b67cb5C2042F38e690
- BeetsWeightedFarm: 1.2.0: 0xDedE7a433444FEfFB6d8A61D80144eF3Ce9982d0
- EqualizerFarmStrategy: 1.2.0: 0x6E12B015F475A92Bd70b530d5DFdF3BF4e10a414
- EulerStrategy: 1.1.0: 0x0c4acAd8cdEd57d82609E9c3227Eb066Fe47C3Ed
- GammaUniswapV3MerklFarmStrategy: 1.6.0: 0x0f558f94cd00374b174514d44211cf9a539e59fd
- IchiSwapXFarmStrategy: 1.3.0: 0x9c6cdc64fc3f43b13deb7971634d838908eb9336
- SiloAdvancedLeverageStrategy: 2.3.0: 0xf89f2a77f900e76d91b0e30847984a008c0e9a31
- SiloFarmStrategy: 1.1.0: 0xAd30Ea4Af9Ea901C2b4F4c78E9cD98A46dE64D6d
- …

305 fix fuse mode

---

script/deploy-periphery/WrappedMetaVaultOracle.wmetaS.Sonic.s.sol

0xB1888CdAae5e3d3e84D2F543c6Ce52e9E36fBAd7

Add oracle for wmetaS

---

chains/sonic/SonicConstantsLib.sol
src/interfaces/IRevenueRouter.sol
src/tokenomics/RevenueRouter.sol
test/tokenomics/RevenueRouter.Upgrade.Sonic.t.sol
test/tokenomics/RevenueRouter.Upgrade2.Sonic.t.sol
test/tokenomics/RevenueRouter.Upgrade3.Sonic.t.sol

* RevenueRouter 1.3.0 https://sonicscan.org/address/0x9ace6d71a3b18fa5eab595f512a380cd42e8a145#code
* RevenueRouter 1.4.0 https://sonicscan.org/address/0xa0e4edf956e8ff9626c5f6eba91c4a2b85c3a42c
* RevenueRouter 1.5.0 https://sonicscan.org/address/0xb789370535ec9e288f8dc3fd39a74e6cf006cefd

RevenueRouter upgrades

---

chains/sonic/SonicConstantsLib.sol
chains/sonic/SonicFarmMakerLib.sol
chains/sonic/SonicLib.sol
script/deploy-strategy/ALMF.s.sol
script/deploy-strategy/AMF.s.sol
src/strategies/AaveMerklFarmStrategy.sol
src/strategies/libs/StrategyDeveloperLib.sol
src/strategies/libs/StrategyIdLib.sol
test/strategies/AMF.Sonic.t.sol

AaveMerklFarmStrategy 1.0.0: 0x7f1449CA301Fe7FEa3a785AfbDc5a525F4A6c38A (partial verification: StrategyLib is not verified)

345 amf aave merkl farm

---

chains/sonic/SonicConstantsLib.sol
src/adapters/MetaVaultAdapter.sol
src/strategies/libs/SiloALMFLib.sol
test/adapters/MetaVaultAdapter.Sonic.t.sol
test/adapters/MetaVaultAdapter.Upgrade101.Sonic.t.sol
test/strategies/SiALMF.Sonic.sol
test/strategies/SiALMF.Upgrade.scUsd.Sonic.t.sol

MetaVaultAdapter 1.0.1: 0x7d6C1D2959BEE3e8b36661A3cA5C76eB7da4DA6f

#348: fix bug in MetaVaultAdapter
